apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "name" . }}
spec:
  volumeClaimTemplates:
    - metadata:
        name: {{ include "name" . }}
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.storageSize }}
  selector:
    matchLabels:
      app: {{ include "name" . }}
  template:
    metadata:
      labels:
        app: {{ include "name" . }}
    spec:
      volumes:
        - name: {{ include "name" . }}
          persistentVolumeClaim:
            claimName: {{ include "name" . }}
      containers:
        - name: main
          image: {{ .Values.image }}
          ports:
            - containerPort: {{ .Values.port }}
          volumeMounts:
            - mountPath: {{ .Values.storagePath }}
              name: {{ include "name" . }}
