apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Chart.Name }}
spec:
  volumeClaimTemplates:
    - metadata:
        name: {{ .Chart.Name }}
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.storageSize }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      volumes:
        - name: {{ .Chart.Name }}
          persistentVolumeClaim:
            claimName: {{ .Chart.Name }}
      initContainers:
        - name: chown
          image: busybox
          command:
            - sh
            - -c
            - chmod 777 -R /data/
          volumeMounts:
            - name: {{ .Chart.Name }}
              mountPath: /data
      containers:
        - name: main
          image: {{ .Values.image }}
          ports:
            - containerPort: {{ .Values.port }}
          volumeMounts:
            - mountPath: {{ .Values.storagePath }}
              name: {{ .Chart.Name }}
