{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}
  labels:
    release: {{ .Chart.Name }}
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.clusterIssuer }}
spec:
  ingressClassName: {{ .Values.ingressClassName }}
  tls:
    - hosts:
        - {{ .Values.ingress.host | default .Values.global.host }}
      secretName:  {{ .Values.ingress.host | default .Values.global.host }}-tls
  rules:
    - host: {{ .Values.ingress.host | default .Values.global.host }}
      http:
        paths:
          - path: {{ .Values.ingress.path | default "/" }}
            pathType: Prefix
            backend:
              service:
                name: {{ .Chart.Name }}
                port:
                  number: 80
{{ end }}
