{{- range $name, $deploy := .Values.deployments }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
spec:
  selector:
    app: {{ $name }}
  ports:
    - port: 80
      targetPort: {{ $deploy.port }}
{{- end }}
