{{- range $name, $ing := .Values.ingresses }}
{{- if $ing.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $name }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - {{ $ing.host | default $.Values.global.host }}
      secretName: {{ $ing.host | default $.Values.global.host }}-tls
  rules:
    - host: {{ $ing.host | default $.Values.global.host }}
      http:
        paths:
          - path: {{ $ing.path | default "/" }}
            pathType: Prefix
            backend:
              service:
                name: {{ $ing.serviceName }}
                port:
                  number: 80
{{- end }}
{{- end }}
